#!/usr/bin/with-contenv sh

PHPFPM_PORT=${PHPFPM_PORT:-80}
PHPFPM_PATH=${PHPFPM_PATH:-"/status"}

if [ -z ${PHPFPM_HOST} ]; then
  echo "Error: no PHP-FPM host specified. Please set the 'PHPFPM_HOST' environment variable"
  exit 1
fi

URI=${PHPFPM_HOST}:${PHPFPM_PORT}${PHPFPM_PATH}
echo "php-fpm status URI: ${URI}"

while true; do
    RESPONSE=$(/usr/bin/wget -qO - ${URI})
    EXIT_STATUS=$?
    if [ $EXIT_STATUS != 0 ]; then
        echo "Error: failed to retrieve status from PHP-FPM. wget exit code was: ${EXIT_STATUS}. wget response was: ${RESPONSE}"
    else
        /bin/echo $RESPONSE
    fi

    /bin/sleep 5

done
