#!/usr/bin/with-contenv sh

PHPFPM_PORT=${PHPFPM_PORT:-80}
PHPFPM_PATH=${PHPFPM_PATH:-"/status"}

if [ -z ${PHPFPM_HOST} ]; then
  echo "Error: no PHP-FPM host specified. Please set the 'PHPFPM_HOST' environment variable"
  exit 1
fi

URI=${PHPFPM_HOST}:${PHPFPM_PORT}${PHPFPM_PATH}
echo "php-fpm status URI: ${URI}"

while true; do
    RESPONSE=$(/usr/bin/wget -qO - ${URI})
    EXIT_STATUS=$?
    if [ $EXIT_STATUS != 0 ]; then
        /bin/echo "phpfpm failure. exit status: ${EXIT_STATUS}. wget response was: ${RESPONSE}"
        # Reset any gauge metrics
        /bin/echo "listen queue: 0 max listen queue: 0 listen queue len: 0 idle processes: 0 active processes: 0 total processes: 0 slow requests: 0"
    else
        /bin/echo "${RESPONSE} phpfpm success"
    fi

    /bin/sleep 5

done
